<?php


namespace app\modules\api;


class Module extends \yii\base\Module
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->user->enableSession = false;
        \Yii::$app->user->enableAutoLogin = false;
        \Yii::$app->user->loginUrl = null;
        \Yii::$app->request->enableCsrfValidation = false;
    }
}